# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\mukai\program\plug-ins\maya\ssds.ui'
#
# Created: Sun Sep  6 14:59:19 2020
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(514, 666)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 471, 631))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spinMinNumJoints = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinMinNumJoints.setMinimum(1)
        self.spinMinNumJoints.setObjectName("spinMinNumJoints")
        self.horizontalLayout.addWidget(self.spinMinNumJoints)
        self.spinMaxNumJoints = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinMaxNumJoints.setMinimum(1)
        self.spinMaxNumJoints.setObjectName("spinMaxNumJoints")
        self.horizontalLayout.addWidget(self.spinMaxNumJoints)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.spinInfluences = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinInfluences.setMinimum(4)
        self.spinInfluences.setMaximum(16)
        self.spinInfluences.setSingleStep(4)
        self.spinInfluences.setProperty("value", 4)
        self.spinInfluences.setObjectName("spinInfluences")
        self.gridLayout.addWidget(self.spinInfluences, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.spinIterations = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinIterations.setProperty("value", 10)
        self.spinIterations.setObjectName("spinIterations")
        self.gridLayout.addWidget(self.spinIterations, 2, 1, 1, 1)
        self.checkUniform = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.checkUniform.setChecked(True)
        self.checkUniform.setObjectName("checkUniform")
        self.gridLayout.addWidget(self.checkUniform, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioRing0 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioRing0.setObjectName("radioRing0")
        self.horizontalLayout_2.addWidget(self.radioRing0)
        self.radioRing1 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioRing1.setObjectName("radioRing1")
        self.horizontalLayout_2.addWidget(self.radioRing1)
        self.radioRing2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioRing2.setChecked(True)
        self.radioRing2.setObjectName("radioRing2")
        self.horizontalLayout_2.addWidget(self.radioRing2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.spinLocality = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.spinLocality.setMaximum(10)
        self.spinLocality.setProperty("value", 5)
        self.spinLocality.setObjectName("spinLocality")
        self.verticalLayout.addWidget(self.spinLocality)
        self.gridLayout.addLayout(self.verticalLayout, 3, 1, 1, 1)
        self.labelNumJoints = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelNumJoints.setObjectName("labelNumJoints")
        self.gridLayout.addWidget(self.labelNumJoints, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(19, 20, 436, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkT = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkT.setObjectName("checkT")
        self.horizontalLayout_3.addWidget(self.checkT)
        self.checkTR = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkTR.setObjectName("checkTR")
        self.horizontalLayout_3.addWidget(self.checkTR)
        self.checkTRS = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkTRS.sizePolicy().hasHeightForWidth())
        self.checkTRS.setSizePolicy(sizePolicy)
        self.checkTRS.setChecked(True)
        self.checkTRS.setObjectName("checkTRS")
        self.horizontalLayout_3.addWidget(self.checkTRS)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.buttonBuild = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.buttonBuild.setObjectName("buttonBuild")
        self.verticalLayout_2.addWidget(self.buttonBuild)
        self.choice = QtWidgets.QListView(self.verticalLayoutWidget)
        self.choice.setObjectName("choice")
        self.verticalLayout_2.addWidget(self.choice)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBuild, QtCore.SIGNAL("clicked()"), Dialog.invokeBuild)
        QtCore.QObject.connect(self.spinMinNumJoints, QtCore.SIGNAL("valueChanged(int)"), Dialog.invokeMinNumChanged)
        QtCore.QObject.connect(self.spinMaxNumJoints, QtCore.SIGNAL("valueChanged(int)"), Dialog.invokeMaxNumChanged)
        QtCore.QObject.connect(self.choice, QtCore.SIGNAL("pressed(QModelIndex)"), Dialog.invokeSelectChoice)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "SSDS", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Dialog", "# Iterations", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Dialog", "Influences", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Dialog", "Locality", None, -1))
        self.checkUniform.setText(QtWidgets.QApplication.translate("Dialog", "Uniform", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Dialog", "Sampling", None, -1))
        self.radioRing0.setText(QtWidgets.QApplication.translate("Dialog", "None", None, -1))
        self.radioRing1.setText(QtWidgets.QApplication.translate("Dialog", "1-Ring", None, -1))
        self.radioRing2.setText(QtWidgets.QApplication.translate("Dialog", "2-Ring", None, -1))
        self.labelNumJoints.setText(QtWidgets.QApplication.translate("Dialog", "# Joints", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("Dialog", "TransformType", None, -1))
        self.checkT.setText(QtWidgets.QApplication.translate("Dialog", "T", None, -1))
        self.checkTR.setText(QtWidgets.QApplication.translate("Dialog", "T+R", None, -1))
        self.checkTRS.setText(QtWidgets.QApplication.translate("Dialog", "T+R+S", None, -1))
        self.buttonBuild.setText(QtWidgets.QApplication.translate("Dialog", "Build", None, -1))

